source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'RBQFRCSwiftExample' do
  pod 'RealmSwift', ">=0.96"
  pod 'RBQFetchedResultsController', :path => '../../'
  pod 'SwiftFetchedResultsController', :path => '../../'

  target 'RBQFRCSwiftExampleTests' do
    inherit! :search_paths
    pod 'RealmSwift', ">=0.96"
  end
end
