source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RBQFetchedResultsControllerExample' do
  pod 'RealmUtilities'
  pod 'RBQSafeRealmObject'

  target 'RBQFetchedResultsControllerExampleTests' do
    inherit! :search_paths
  end
end
