source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RBQFetchedResultsControllerExample' do
    pod 'Realm', '>= 0.95'
    pod 'RBQFetchedResultsController', :path => '../../'

    target 'RBQFetchedResultsControllerExampleTests' do
        inherit! :search_paths
        pod 'Realm/Headers'
    end
end
