# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'RBQFRCDynamicExample' do
  pod "Realm"
end

target 'RBQFRCDynamicExampleTests' do
  pod "Realm/Headers"
end

