platform :ios, '8.0'

target 'RBQFetchedResultsControllerExample', exclusive: true do
    pod 'Realm'
    pod 'RBQFetchedResultsController'
end

target 'RBQFetchedResultsControllerExampleTests', exclusive: true do
    pod 'Realm/Headers'
end