platform :ios, '8.0'

target 'RBQFetchedResultsControllerExample', exclusive: true do
    pod 'Realm', '= 0.90.2'
end

target 'RBQFetchedResultsControllerExampleTests', exclusive: true do
    pod 'Realm/Headers', '= 0.90.2'
end