source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RBQFetchedResultsControllerExample' do
    pod 'Realm', '~> 0.93.0'
    pod 'RBQFetchedResultsController'
end

target 'RBQFetchedResultsControllerExampleTests' do
    pod 'Realm/Headers'
end